"""carfac-ephys: Simulating animal cochlear impairment electrophysiology with CARFAC."""

from carfac_ephys.carfac_model import (
  CarfacModel,
  FiberRetention,
  build_model,
)
from carfac_ephys.constants import (
  DEFAULT_SAMPLE_RATE,
  DYNAMIC_RANGE_DB,
  amplitude_to_db_spl,
  db_spl_to_amplitude,
)
from carfac_ephys.electrophysiology import (
  RESPONSE_UNIT,
  compute_population_rate,
  extract_efr_amplitude,
  extract_wave_i_amplitude,
  fit_microvolts_per_au,
)
from carfac_ephys.empirical import (
  CLICK_FREQUENCY_HZ,
  DEFAULT_DATA_DIR,
  AnimalWaveAmplitudes,
  ChinchillaAbrDataset,
  PrePostStat,
  load_chinchilla_abr_dataset,
)
from carfac_ephys.experiment import (
  DEFAULT_CLICK_LEVELS_DB,
  DEFAULT_COHORT_CONDITIONS,
  DEFAULT_EFR_LEVELS_DB,
  DEFAULT_TONE_BURST_FREQUENCIES_HZ,
  DEFAULT_TONE_BURST_LEVELS_DB,
  BiologicalValidation,
  Cohort,
  CohortCondition,
  EmpiricalComparison,
  ToneBurstCohortResults,
  ToneBurstEmpiricalComparison,
  compare_to_empirical,
  compare_tone_burst_to_empirical,
  estimate_threshold_db,
  fit_response_scale_uv_per_au,
  format_calibration_line,
  format_empirical_comparison_table,
  format_markdown_table,
  format_tone_burst_comparison_table,
  generate_simulation_report,
  get_default_cohort,
  plot_abr_growth,
  plot_efr_growth,
  plot_empirical_comparison,
  plot_tone_burst_growth,
  plot_tone_burst_waveforms,
  simulate_abr_level_series,
  simulate_efr_level_series,
  simulate_tone_burst_abr_series,
  simulate_tone_burst_cohort,
  simulate_tone_burst_waveforms,
  validate_biological_signatures,
)
from carfac_ephys.stimuli import (
  generate_click,
  generate_sam_tone,
  generate_tone_burst,
  generate_tone_burst_train,
)

__version__ = "0.1.0"

__all__ = [
  "CLICK_FREQUENCY_HZ",
  "DEFAULT_CLICK_LEVELS_DB",
  "DEFAULT_COHORT_CONDITIONS",
  "DEFAULT_DATA_DIR",
  "DEFAULT_EFR_LEVELS_DB",
  "DEFAULT_SAMPLE_RATE",
  "DEFAULT_TONE_BURST_FREQUENCIES_HZ",
  "DEFAULT_TONE_BURST_LEVELS_DB",
  "DYNAMIC_RANGE_DB",
  "RESPONSE_UNIT",
  "AnimalWaveAmplitudes",
  "BiologicalValidation",
  "CarfacModel",
  "ChinchillaAbrDataset",
  "Cohort",
  "CohortCondition",
  "EmpiricalComparison",
  "FiberRetention",
  "PrePostStat",
  "ToneBurstCohortResults",
  "ToneBurstEmpiricalComparison",
  "amplitude_to_db_spl",
  "build_model",
  "compare_to_empirical",
  "compare_tone_burst_to_empirical",
  "compute_population_rate",
  "db_spl_to_amplitude",
  "estimate_threshold_db",
  "extract_efr_amplitude",
  "extract_wave_i_amplitude",
  "fit_microvolts_per_au",
  "fit_response_scale_uv_per_au",
  "format_calibration_line",
  "format_empirical_comparison_table",
  "format_markdown_table",
  "format_tone_burst_comparison_table",
  "generate_click",
  "generate_sam_tone",
  "generate_simulation_report",
  "generate_tone_burst",
  "generate_tone_burst_train",
  "get_default_cohort",
  "load_chinchilla_abr_dataset",
  "plot_abr_growth",
  "plot_efr_growth",
  "plot_empirical_comparison",
  "plot_tone_burst_growth",
  "plot_tone_burst_waveforms",
  "simulate_abr_level_series",
  "simulate_efr_level_series",
  "simulate_tone_burst_abr_series",
  "simulate_tone_burst_cohort",
  "simulate_tone_burst_waveforms",
  "validate_biological_signatures",
]

